<template>
<div class="nav-bar">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <router-link class="navbar-brand" to="/">{{navBrand}}</router-link>
    <button
          v-on:click="search__open"
          class="search__button">
        <img class="search__image" src="../images/Search_Icon.png" >
    </button>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li
          v-for="(path, label, index) in navList" :key="index"
          class="nav-item dropdown">
          <router-link
            v-if="typeof(path) == 'string'"
            class="nav-link" :to="path">
            {{ label }}
          </router-link>
          <template v-else-if="typeof(path) == 'object'">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdownMenuLink"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false">
              {{ label }}
            </a>
            <div
              class="dropdown-menu"
              aria-labelledby="navbarDropdownMenuLink">
              <router-link
                v-for="(path, label, index) in path" :key="index"
                class="dropdown-item"
                :to="path">
                {{ label }}
              </router-link>
            </div>
          </template>
        </li>
      </ul>
        <div class="nav-item nav-link number">+99119998877</div>
        <div class="links">
          <span class="instagram__container"><a href=""><img class="instagram white-icon" src="../images/instagram.png" alt=""></a></span>
          <span class="facebook__container"><a href=""><img class="facebook white-icon" src="../images/facebook.png" alt=""></a></span>
        </div>
        <div class="languages">
          <a href="#" class="russian">Ru</a>
          <span> | </span>
          <a href="#" class="english">En</a>
        </div>
    </div>
  </nav>
  <div id="div_searcher" class="seach_container scale-out-top closed">
      <input v-model="searchF" id="search_inDiv" type="text" class="form-control" placeholder="Поиск по сайту...">
      <button
            v-on:click="search__reload"
            class="search__image_incontainer">
          <img class="search__image" src="../images/Search_Icon.png" >
      </button>
  </div>
</div>
</template>

<script>
export default {
  name: 'navigation',
  data () {
    return {
      searchF: ''
    }
  },
  props: {
    navList: Object,
    navBrand: String
  },
  methods: {
    search__open: function (event){
      var element = document.getElementById("div_searcher");
      if (element.classList.contains("closed")){
        element.classList.remove("closed");
        element.classList.remove("search__container_disable");
        element.classList.add("slide-in-top");
        element.classList.add("opend");
        element.classList.remove("scale-out-top");
      } else {
        element.classList.remove("slide-in-top");
        element.classList.remove("opend");
        element.classList.add("scale-out-top");
        element.classList.add("closed");
        element.classList.add("search__container_disable");
      }
      // Пойду посу, может настроение поднимиться. Павел Усатенко©

    },
    search__reload: function (event){
      this.createLocalStorage();
      this.searchF = '';
      this.$router.push('/search');
    },
    takeSearch(){
          return this.$store.getters.takeSearch;
    },
    rewriteTokens(){
      if(this.searchF){
          this.$store.dispatch('writeSearch', this.searchF)
        }
    },
    createLocalStorage(){
        this.rewriteTokens()
        window.localStorage.setItem('search',this.takeSearch())
    },
  },
}
</script>

<style>
.nav-bar {
  z-index: 10;
}

.scale-out-top {
	-webkit-animation: scale-out-top 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
	        animation: scale-out-top 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-3-15 23:23:29
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-out-top
 * ----------------------------------------
 */
@-webkit-keyframes scale-out-top {
  0% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-transform-origin: 50% 0%;
            transform-origin: 50% 0%;
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(0);
            transform: scale(0);
    -webkit-transform-origin: 50% 0%;
            transform-origin: 50% 0%;
    opacity: 1;
  }
}
@keyframes scale-out-top {
  0% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-transform-origin: 50% 0%;
            transform-origin: 50% 0%;
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(0);
            transform: scale(0);
    -webkit-transform-origin: 50% 0%;
            transform-origin: 50% 0%;
    opacity: 1;
  }
}

.slide-in-top {
	-webkit-animation: slide-in-top 1s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: slide-in-top 1s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

@-webkit-keyframes slide-in-top {
  0% {
    -webkit-transform: translateY(-10px);
            transform: translateY(-10px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}
@keyframes slide-in-top {
  0% {
    -webkit-transform: translateY(-10px);
            transform: translateY(-10px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}


.seach_container{
  z-index: 1;
  margin-left: 40px;
  margin-right: 40px;
  background: rgba(97, 139, 170, 0.78);
  border:#595C61;
  border-radius: 0px 0px 10px 10px;
  max-width: 290px;
  padding: 10px 5px;
  
  height: 50px;
}
.form-control{
  background: #4D677E;
  border-radius: 2px 0px 0px 2px;
  border-color:#4D677E;
  color: #000000;
  
  height: 30px;
}
.search__button{
  background: transparent;
  border: none !important;
  font-size:0;
}
.search__image {
  width: 20px;
}
.search__image_incontainer {
  position: absolute;
  background: transparent;
  border: none !important;
  font-size:0;
  right: 5px;
  top:14px;
}
</style>

<style lang="scss" scoped>
.navbar {
  background: rgba(97, 139, 170, 0.78);
  font-size: 18px;
  margin: 8px;
  border-radius: 10px;
  padding-top: 0;
  padding-bottom: 0;
  margin-left: 30px;
  margin-right: 30px;
  margin-bottom: 0px;

  .navbar-brand {
    font-size: 35px;
    font-family: Sedan;
    display: inline-block;
    margin-bottom: 0;
  }

  .dropdown-menu{
    background: rgba(97, 139, 170, 0.7);
    margin: 0;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
    border: none;
  }

  .dropdown-item {
    color: #fff;
  }

  .dropdown-item:hover{
    background: rgba(255, 255, 255, 0);
    color: #fff;
  }
  .number{
    margin-left: auto;
    color: #fff;
    font-family: Montserrat;
    font-style: normal;
    font-weight: 300;
  }

  .instagram, .facebook{
    width: 25px;
  }

  .facebook:hover {
    filter: invert(0);
    width: 25px;
  }

  .instagram:hover {
    filter: invert(0);
    width: 25px;
  }

  .white-icon{
      filter: brightness(0) invert(1);
  }

  .russian, .english{
    color:#fff;
    text-decoration: none;
  }
  .languages{
    color: #fff;
    margin-left: 10px;
    font-family: Sedan;
  }
  .russian, .english:hover{
      color: #fff;
  }
  .dropdown:hover .dropdown-menu {
  display: block;
  }
  .dropdown-menu:hover {
  display: block;
  }

  @media (max-width: 991px) {
    .languages{
      margin: 0;
    }
    .number{
      padding: 0;
    }
    .instagram__container, .facebook__container{
      display: inline;
    }

  }
}
</style>
